spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fullstack
    username: root
    password: my0504
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# ?? ? ?? ??? ?? ?? ???? gzip?? ??
server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json, application/zip, application/octet-stream, image/jpeg, image/png
    min-response-size: 500

papago:
  url:
    detect: "https://openapi.naver.com/v1/papago/detectLangs"
    translate: "https://openapi.naver.com/v1/papago/n2mt"
